name = "UFDTD"
uuid = "cdc4ecdc-08f4-47d4-adff-7df93aadf864"
authors = ["MKAbdElrahman <smohamed.abdelrahman@gmail.com>"]
version = "0.1.0"

[deps]
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
